// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxaS6UdeItNcWJ0p3XHdMV-hJQQ_8uhvw',
    appId: '1:640858425141:web:5b4516ffba5ecb17a22e7c',
    messagingSenderId: '640858425141',
    projectId: 'anki-shared-c263b',
    authDomain: 'anki-shared-c263b.firebaseapp.com',
    storageBucket: 'anki-shared-c263b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMlxMWDHYsydtO0JWxQzI3LAWrfrW9yDA',
    appId: '1:640858425141:android:ca3e8e4c69d2a54aa22e7c',
    messagingSenderId: '640858425141',
    projectId: 'anki-shared-c263b',
    storageBucket: 'anki-shared-c263b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKQkfoupvrKikG57BmZVQaXHPIMYpT7wk',
    appId: '1:640858425141:ios:8f0a8f2e27a97242a22e7c',
    messagingSenderId: '640858425141',
    projectId: 'anki-shared-c263b',
    storageBucket: 'anki-shared-c263b.firebasestorage.app',
    iosBundleId: 'com.example.ankiFlutter',
  );
}
